name: v3c_gsc_video_integration_152_test
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10

  # GPU and ML libraries
  - pytorch=2.4
  - pytorch-cuda=12.1
  - torchvision=0.19

  # Common scientific stack
  - numpy=1.26
  - pandas=2.2
  - scipy=1.14
  - matplotlib=3.8
  - scikit-learn=1.4

  # Others
  - tqdm=4.67
  - pip=24.3
  - plyfile=1.1
  - ffmpeg=4.4 # CLI tool
  - ffmpeg-python  # Python wrapper
  - bitarray
  - trimesh
  - rich  
  - ninja 
  - cmake            
  - setuptools
  - wheel
  - openpyxl
  - commentjson
  - bjontegaard

  - pip:
      - git+https://github.com/jyj0121/RectangularPLAS.git
      - ./utils/pruning  
